#!/bin/bash

export FILE=FY2014_50_Final.xls

wget -O test/data/$FILE http://www.huduser.org/portal/datasets/50thper/$FILE;

export FILE=qct_data_seattle.xls

echo "Getting QCT data...";
wget -O test/data/$FILE \
	http://qct.huduser.org/tables/qct_data_extract_2015.xls.odb?cbsa=42660;
echo "Got QCT data";

node test/xls.js;

